version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - "386"
    - amd64
    - arm
    - arm64
  goarm:
    - "7"
  ignore:
  - goos: windows
    goarch: arm64
  - goos: windows
    goarch: arm
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.Version={{.Version}}

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch', 'go mod tidy']

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
    - goos: windows
      formats:
        - zip
    files:
    - README.md
    - LICENSE.md

homebrew_casks:
  - repository:
      owner: kha7iq
      name: homebrew-tap
    homepage: https://pingme.lmno.pk
    description: PingMe is a CLI tool which provides the ability to send messages or alerts to multiple messaging platforms.
    license: MIT

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    maintainer: 'Abdul Khaliq <a.khaliq@outlook.my>'
    homepage: https://pingme.lmno.pk
    description: PingMe is a CLI tool which provides the ability to send messages or alerts to multiple messaging platforms.
    license: MIT
    formats:
    - deb
    - rpm
    dependencies:
    - git

scoops:
- repository:
    owner: kha7iq
    name: scoop-bucket
  url_template: "https://github.com/kha7iq/pingme/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: https://pingme.lmno.pk
  description: PingMe is a CLI tool which provides the ability to send messages or alerts to multiple messaging platforms.
  license: MIT

dockers_v2:
- images:
  - 'khaliq/pingme'
  - 'ghcr.io/kha7iq/pingme'
  tags:
  - '{{ .Tag }}'
  - 'latest'
  platforms:
  - linux/amd64
  - linux/arm64
  labels:
    "org.opencontainers.image.created": "{{.Date}}"
    "org.opencontainers.image.name": "{{.ProjectName}}"
    "org.opencontainers.image.revision": "{{.FullCommit}}"
    "org.opencontainers.image.version": "{{.Version}}"
    "org.opencontainers.image.source": "{{.GitURL}}"
