name: pingme
version: git
summary: A command line tool to send a message with particular information
description: |
  PingMe is a personal project to satisfy my needs of having alerts, most major platforms have integration to send alerts but its not always useful, either you are stuck with one particular platform, or you have to do alot of integrations. I needed a small app which i can just call from my backup scripts, cron jobs, CI/CD pipelines or from anywhere to send a message with particular information. And i can ship it everywhere with ease. Hence, the birth of PingMe.
  Everything is configurable via environment variables, and you can simply export the logs or messages to a variable which will be sent as message. And most of all this serves as a swiss army knife sort of tool which supports multiple platforms.


architectures:
  - build-on: arm64
  - build-on: amd64
assumes: [snapd2.45]
base: core18

grade: stable
confinement: strict


apps:
  pingme:
    command: bin/pingme
    plugs:
      - home
      - network
      - network-bind
      
parts:
  pingme:
    source: .
    plugin: go
    go-importpath: https://github.com/kha7iq/pingme
    build-packages:
      - gcc-multilib
    go-buildtags:
      - pingme
    override-build: 
      go build  -o ../install/bin/pingme


